### ISSUE TITLE
Connect IAM backend

### ISSUE THREAD

**Issue by sbagg** [UCDavisLibrary/ucdlib-iam-support#25]

**Comment by spelkey-ucd** [comment]
We will need a custom API endpoint that allows for bulk querying of the `people/profile/search` UCD IAM endpoint because this ucd endpoint returns pretty much all info on a person that the system has access to. However, it is only queryable by iamid, kerb, and email.

so the new endpoint should take a list of comma-separated iamIds. And then use `promise.all` to make concurrent requests to `UcdIamModel.getPersonByIamId`.

You will want to chunk your requests (start with 5?), so we don't tax resources with too many concurrent requests.
some pseudo code:
```js
const queryLimit = config.ucdIamApi.queryLimit;
const iamIds = req.query.ids.split(',').map(id => id.trim()).slice(0, queryLimit);

// returns array of arrays [[id1,id2,id3,id4,id5], [id6,id7,id8,id9,id10], etc]
const maxConcurrentRequests = config.ucdIamApi.maxConcurrentRequests || 5;
const chunks = chunkArray(iamIds, maxConcurrentRequests)

const people = [];
for (const chunk of chunks) {
  const promises = chunk.map(id => UcdIamModel.getPersonByIamId(id));
  await Promise.all(promises);
  people.push(...promises);
}

```
